### ISSUE TITLE
pip_find_builddeps.py gives exception processing flit_core

### ISSUE THREAD

**Issue by tmckayus** [release-engineering/cachito#363]
When I run this command, it fails processing flit_core (sample log attached)

./pip_find_builddeps.py requirements.txt -o requirements-build.in --append

Running on F32 with Python 3.8

[pip-download-output.txt](https://github.com/release-engineering/cachito/files/5897013/pip-download-output.txt)

[requirements.txt](https://github.com/release-engineering/cachito/files/5897008/requirements.txt)

**Comment by tmckayus** [comment]
@arewm

**Comment by chmeliik** [comment]
What version of pip do you have installed? If it is `pip<20`, then you are running into the following issue: https://github.com/pypa/pip/issues/6599

In order for the `pip_find_builddeps.py` run to fully succeed with your requirements file, you will need:
* `pip>=20.0`
* `gcc python-devel libxml2-devel libxslt-devel libffi-devel openssl-devel`

These are the outputs:
* requirements-build.in: https://pastebin.com/M0j05zcn
* requirements-build.txt: https://pastebin.com/ZcijBjhC
---
If you're wondering why, here is a few fun facts about Python build dependencies and what you need to do in order to download them.

First, the reason why you need `pip>=20.0`. After [PEP 517](https://www.python.org/dev/peps/pep-0517/), Python now supports build backends other than setuptools. To get the build dependencies for a package, you must first install the build backend specfied in [pyproject.toml](https://github.com/takluyver/flit/blob/master/flit_core/pyproject.toml) (this is the one for flit_core). You then call the `get_requires_for_build_wheel()` hook from the build backend, which returns a list of build dependencies. As you may have noticed, the build backend for flit_core is, well, flit_core. This is specified via the `backend-path` option, which is not supported in `pip<20`.

Second, the reason why you need `gcc` and all the development headers. PEP 517 only specifies a hook for getting build dependencies. To get *runtime* dependencies, your only option is the `prepare_metadata_for_build_wheel()` hook which creates, among other things, a `.dist-info/METADATA` file which you then have to parse to find the runtime deps. As mentioned in the PEP, this hook will often fall back to using `build_wheel()` and extracting the metadata from the built wheel. This is the case for setuptools. Therefore, to get the runtime deps of a package, you need to build the package. If that package only has pure python build dependencies, that is not an issue. However, as seen here, packages written in C will require you to install headers yourself.

You may be thinking that extracting the runtime deps is not necessary here, since they are present in the input requirements file already. This is partially true, but pip unfortunately does not know that. Another issue is that the build deps may have additional runtime deps, so even if we could tell pip to download only build deps, the results would not necessarily be complete.

---
Regarding the development headers problem, unfortunately, I cannot think of any easier solution then re-running `pip_find_builddeps.py` again and again until all the issues have been fixed. That's what I did, and it took me 6 tries.

If you don't mind having a bunch of extra development headers lying around, you could do something like `dnf group install 'Development Libraries'` (perhaps in a dedicated container), this would get you most of the headers that you will need.

**Comment by tmckayus** [comment]
@chmeliik thanks! I upgraded to F33 with pip 20 and it works
